### ISSUE TITLE
show reply when uploading

### ISSUE THREAD

**Issue by Quackdoc** [mihaigalos/aim#149]
aim doesn't currently show the reply when an upload happens, this makes services like transfer.sh or 0x0.st unusable

usage 
`aim file.txt http://0x0.st`
`aim file.txt http://transfer.sh/file.txt`

example curl 
```
curl -F file=@file.txt http://0x0.st
link to file here
```
```
curl --upload-file file.txt https://transfer.sh/file.txt
link to file here 
```

**Comment by mihaigalos** [comment]
Hi @Quackdoc,

Thanks for reporting the bug.
 `0x0.st` doesn't support `PUT` operations, only `POST`.
 `transfer.sh` does.

Anyway, I'm adding a print line for the server reply for `transfer.sh`.

I don't have `POST` operations for uploading on the roadmap right now, but feel free to contribute a PR.

**Comment by mihaigalos** [comment]
`0x0.st` upstream feature request for `PUT`: https://git.0x0.st/mia/0x0/issues/62.
