### ISSUE TITLE
Genius - ?

### ISSUE THREAD

**Issue by firasuke** [mihaigalos/aim#17]
Genius.

_Originally posted by @mihaigalos in https://github.com/mihaigalos/aim/issues/16#issuecomment-1004083064_

Is this the correct way to deal with those interested in your project? What more information should I provide to better describe my use case than wanting to download multiple files in parallel?

Sigh...

**Comment by mihaigalos** [comment]
Thanks for your concern. Please stop spamming. I will otherwise report the behavior to GitHub.
