### ISSUE TITLE
mosh support

### ISSUE THREAD

**Issue by ShalokShalom** [mihaigalos/aim#23]
[mosh.io](mosh.io)
https://github.com/mobile-shell/mosh

This is ssh, just better.

Like aim for ssh. 

I suggest supporting it 😇

**Comment by mihaigalos** [comment]
Hi @ShalokShalom, what do you mean? I don't follow.

**Comment by ShalokShalom** [comment]
Mosh is an alternative to ssh. 
It's still using ssh for authentication, but everything else is different 

The benefits are, that you have no broken pipe, since its UDP on the server side, and you are connecting to a buffer.

That means when you are roaming (switching between wlan and usim) or simply loose connection, you can just pickup where you left and all input is saved.

This also helps to give much better feedback on keystrokes and to ctrl+c the process. 

Like to see it supported by aim, if possible.

**Comment by mihaigalos** [comment]
@ShalokShalom : how do you envision `mosh` support? How would `aim` differentiate between pure **ssh** and **mosh**?
It currently knows by looking ad the `ssh://` prefix.

Do you know of any self-contained rust implementations of a `mosh` client? I would not want to reinvent the wheel and use one here.
If not, I'm afraid one is necessary first in order for this issue to continue.

**Comment by ShalokShalom** [comment]
I didnt think about a Rust implementation, as I thought the client side might be fairly trivial to program.
