### ISSUE TITLE
Executable name overlap

### ISSUE THREAD

**Issue by jarnos** [mihaigalos/aim#30]
Where does the name come from? Maybe not a big issue, but ABINIT package has `aim` executable, too. See [the doc](https://docs.abinit.org/guide/aim/). (abinit package is available in the universe/science repository of Ubuntu.)

**Comment by mihaigalos** [comment]
Hi @jarnos,
Initially I "aimed" the tool at an file URL to download it. Hence the naming.
I like the naming because you can "aim from X" and "aim to Y", the same way you would use redirection in a shell.

Took a look at the doc, not very familiar with `ABINIT` but it seems a cool project.

**Comment by mihaigalos** [comment]
I'm closing this issue since I would like to keep the current naming.
